name: 🧪 Test ConstructionVRTForTheFlightService

on:
  push:
    paths:
      - "ConstructionVRTForTheFlightService/**"
      - ".github/workflows/ConstructionVRTForTheFlightService.yaml"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📂 Checkout
      uses: actions/checkout@v3
    
    - name: 🔵 Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
        cache: 'pip'

    - name: ⏬ Install dependencies
      run: |
        pip install -r ConstructionVRTForTheFlightService/requirements.txt

    - name: ✅ Run tests
      run: |
        pytest
  